#!/bin/bash

set -o errexit
set -o nounset

readonly DIR="$(dirname $(realpath $0))/configs"

readonly BASHRC=~/.bashrc
readonly BASH_PROFILE=~/.bash_profile

if [[ -f ${BASHRC} ]]; then
    BASH_CONFIGS="${BASHRC}"
else
    BASH_CONFIGS="${BASH_PROFILE}"
fi

if ! grep -q "${DIR}/bash.sh" "${BASH_CONFIGS}"; then
    echo "source ${DIR}/bash.sh" >> "${BASH_CONFIGS}"
fi

mkdir -p ~/.config/git
if [ ! -e ~/.config/git/config ]; then 
    ln -s "${DIR}/gitconfig" ~/.config/git/config
fi

mkdir -p ~/.emacs.d
if [ ! -e ~/.emacs.d/init.el ]; then
    ln -s "${DIR}/emacs.el" ~/.emacs.d/init.el
fi

if [ ! -e ~/.tmux.conf ]; then
    ln -s "${DIR}/tmux.conf" ~/.tmux.conf
fi
