#!/usr/bin/env bash

# Creates symlinks for the contents of configs/ in the home dir.

set -e  # Fail on first error.

# A hack to get around the fact that there is nothing like realpath
# installed by default on Mac OS X.
REALPATH=$(python -c "import os; print os.path.realpath('${0}')")

DIR=$(dirname ${REALPATH})/configs
FILES=$(ls -A ${DIR})

echo $FILES
for file in ${FILES}; do
    [[ -e ~/${file} ]] || ln -s ${DIR}/${file} ~/${file}
done
